### PR TITLE
fix(web): promoted data key

### PR DESCRIPTION
**Pull request by ShahAnuj2610**

### CODE REVIEW

**Review by bietkul — CHANGES_REQUESTED** [review]
@ShahAnuj2610 Change in `StateProvider` too.

**Comment by ShahAnuj2610** [comment]
> @ShahAnuj2610 Change in `StateProvider` too.

It's done in the corresponding `reactivecore`

**Comment by bietkul** [comment]
> > @ShahAnuj2610 Change in `StateProvider` too.
> 
> It's done in the corresponding `reactivecore`

@ShahAnuj2610 I don't think it'll work in that way, can you verify?

**Comment by ShahAnuj2610** [comment]
> > > @ShahAnuj2610 Change in `StateProvider` too.
> > 
> > 
> > It's done in the corresponding `reactivecore`
> 
> @ShahAnuj2610 I don't think it'll work in that way, can you verify?

it works

**Pull request merged**
