### PR TITLE
refactor(vue): styles for DataSearch

### PR DESCRIPTION
**Pull request by ShahAnuj2610**
- [x]  Fix icon styles
    - [x]  Alignment is off
    - [x]  There's an overlap issue
- [x]  Fix max-height for suggestions to show min 10 rows (this also applies to Searchbox libraries). We currently show a scroll.
- [x]  increase `max-width` to avoid scroll

### CODE REVIEW

**Review by jyash97 — COMMENTED** [review]
In this PR we aren't fixing the color for svg or we have different PR for that

**Comment by ShahAnuj2610** [comment]
> In this PR we aren't fixing the color for svg or we have different PR for that

we don't have `Mic` component here

**Comment by jyash97** [comment]
So in vue we don't have voice search ?

**Comment by ShahAnuj2610** [comment]
> So in vue we don't have voice search ?

no

**Pull request merged**
