### PR TITLE
web : Add includeUnrated in RatingsFilter

### PR DESCRIPTION
**Pull request by jyash97**
#267 

Getting a prop-type error in `SelectedValue`, rest everything is working 💯

### CODE REVIEW

**Comment by davidklebanoff** [comment]
Does this cover both possible cases, when the rating is `undefined` or `0`?

**Comment by davidklebanoff** [comment]
> `rating:0` can be specified in the data object

Good point!

**Comment by jyash97** [comment]
They are getting set on `URL` as : `http://localhost:8001/?RatingsSensor=%5B3%2C5%2Ctrue%5D`

`true` is the value passed to `includeUnrated`.
It is applying on reloading the URL when `URLParams` is `true`

**Comment by bietkul** [comment]
@jyash97 Can we close it now?
I think it has been done here #1003

**Comment by jyash97** [comment]
Yeah this can be closed this was meant for v2. Already fixed in #1003

**Pull request closed without merging**
