### PR TITLE
chore: add release drafter

### PR DESCRIPTION
**Pull request by lakhansamani**
### Setup

* For release drafter to work correctly, we need to make `next` branch as the default branch or need to merge all changes into `dev`.
* In order to categories commits into `feature`, `fix` and `chore` we need to add respective labels to PR before merging them.

### CODE REVIEW

**Review by jyash97 — COMMENTED** [review]
Is there any way we can differentiate `React`, `Vue` and `Native` changes? 

Also, we can add a `PR labeler` or `Probot` to automatically add the respective labels, wdyt ?

**Comment by lakhansamani** [comment]
Yes, we can differentiate between React, Vue, Native for the release, but I think, that should be part of tagging, eg. `react-v3.0`, WDYT?

**Comment by jyash97** [comment]
Not too sure, but I think it should work. What about probot for automatic tagging ?

**Comment by lakhansamani** [comment]
Yes, will research on that and will try to integrate it.

**Comment by jyash97** [comment]
We can integrate it later, for now release drafter makes more sense 👍

**Review by jyash97 — APPROVED** [review]

**Pull request merged**
