### PR TITLE
[enh]: Introduce new prop in ReactiveList to render last pages in pagination [WIP]

### LINKED ISSUE #633: Pagination customization: get last page
**Issue Type:** enhancement

**Platform:** web

**Description+Screenshots:**
Currently, the pagination only displays the N first page (and not the last one) : 

capture d ecran 2018-11-28 a 16 12 56

It could be great if we could display something like this (with the last page): 

zrjowucfrgwclsvoxhzbdw

**Reactivesearch version:** 2.11.0

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #633

### CODE REVIEW

**Comment by anshumanv** [comment]
Working on some end cases, do lmk if lock file is to be removed.

**Review by bietkul — APPROVED** [review]

**Comment by bietkul** [comment]
@anshumanv The PR looks good, Can you share some screenshots or gif which showcase the UI and working.

**Review by bietkul — CHANGES_REQUESTED** [review]
The PR must be targeted for the `next` branch.

**Comment by anshumanv** [comment]
Sure @bietkul will share a working gif in a while thanks ✨

**Comment by bietkul** [comment]
@anshumanv Any update on this?

**Comment by anshumanv** [comment]
start
image

mid
image

end
image

**Comment by anshumanv** [comment]
Sorry for the delay, here are some snaps of how it looks.

Seems good to go! 🚀 @bietkul

**Comment by siddharthlatest** [comment]
@anshumanv Would the next button be disabled when on the last page? Can you share a GIF showing the transitions?

**Comment by bietkul** [comment]
@anshumanv Can you please port these changes to the `next` branch, where we're doing the active development.

**Comment by anshumanv** [comment]
Aug-06-2019 20-16-21

@siddharthlatest here, sure @bietkul on it.

**Comment by anshumanv** [comment]
@bietkul changed base

**Review by bietkul — CHANGES_REQUESTED** [review]
@anshumanv Can you add `showEndPage` in `ReactiveList.ts` too?

**Comment by anshumanv** [comment]
Ahh forgot about definitions,

@bietkul ptal ✨

**Comment by anshumanv** [comment]
ping @bietkul

**Review by bietkul — APPROVED** [review]

**Pull request merged**
