### PR TITLE
feat(vue): voice search

### PR DESCRIPTION
**Pull request by ShahAnuj2610**
docs: https://github.com/appbaseio/Docs/pull/109

### CODE REVIEW

**Comment by ShahAnuj2610** [comment]
Working GIF:

**Comment by ShahAnuj2610** [comment]
Few UI scenarios test:

- {showClear: true, showVoiceSearch: true, iconPosition: left}



- {showClear: false, showVoiceSearch: true, iconPosition: left}



- {showClear: false, showVoiceSearch: true, iconPosition: right}



- {showClear: true, showVoiceSearch: true, iconPosition: right}

**Review by jyash97 — CHANGES_REQUESTED** [review]
- Color difference: 
image

- After the recognition is complete the mic still listens. It should stop after successful recognition
image

**Review by jyash97 — COMMENTED** [review]
- When there is no permission for a mic, we can toggle it. Check this: 
Denied_Mic

**Comment by jyash97** [comment]
> After the recognition is complete the mic still listens. It should stop after successful recognition

This issue is not addressed in the latest commit.

Here is the gif demonstrating the issue:
Voice_search

**Review by jyash97 — APPROVED** [review]

**Pull request merged**
