### PR TITLE
Set search params

### PR DESCRIPTION
**Pull request by rap2hpoutre**
Since we could consider the "history" issue (params and back/forward) as a bug (https://github.com/appbaseio/reactivesearch/issues/823, https://github.com/appbaseio/reactivesearch/pull/572, https://github.com/appbaseio/reactivesearch/issues/824, https://github.com/appbaseio/reactivesearch/issues/186, etc.) which has a workaround here: https://github.com/appbaseio/reactivesearch/commit/2b631955e0ddef8f48b79e341c146b4f58ca5e84 😍  (thank you @metagrover! 👍), I think we could backport this functionality to current version (I mean 2.x, so it could be 2.17). 3.x branch seems to have some incompatible change and IMO, we could consider fix this router/history issue in v2.x.

I just tried this fix here with a temporary fork (https://www.npmjs.com/package/rap2h-reactivesearch) and it _seems to work_.

Do you think you could merge it and release it?

### CODE REVIEW

**Comment by metagrover** [comment]
Hi @rap2hpoutre thanks for taking out time for this.

Just to be super clear, is this the port of set/get searchParams from `next` (3.0) to `2.x`?

**Comment by rap2hpoutre** [comment]
> Just to be super clear, is this the port of set/get searchParams from next (3.0) to 2.x?

Yes, exactly!

More info: I took this commit https://github.com/appbaseio/reactivesearch/commit/2b631955e0ddef8f48b79e341c146b4f58ca5e84 and adapted it to match in the 2.x versions of files.

**Comment by metagrover** [comment]
awesome! 🎉

**Review by metagrover — APPROVED** [review]

**Comment by metagrover** [comment]
Thanks again! I will do a (2.x) release later today to ship this 🐱

**Comment by rap2hpoutre** [comment]
@metagrover Thank you! Do you have a release date for 2.x?

**Comment by metagrover** [comment]
Thanks for the patience! `2.17.0` is out 🎉

**Pull request merged**
