### PR TITLE
feat(web): searchbox bugs and search enhancements

### PR DESCRIPTION
**Pull request by SavvyShah**
[Notion Card - Searchbox issues](https://www.notion.so/reactivesearch/ReactiveSearch-SearchBox-Issues-0eb7f15b6aae4e7f93296c1086405f6f)
[Notion Card - Searchbox enhancement](https://www.notion.so/reactivesearch/ReactiveSearch-SearchBox-Enhancements-620b21dd989a4c8cb388209f3052811a)

[Loom preview](https://www.loom.com/share/b2be89a15ade4d8b947b85144d515307)

Enhancements
--------------
- iconURL property(precedence over icon prop)
- suggestions footer showing navigation information

### CODE REVIEW

**Review by bietkul — CHANGES_REQUESTED** [review]
### UI Issues
- Focus shortcut icon should have proper margins and padding, colors should match the theme.
alt icon
- How is iconURL rendered? What if a user is using an over-sized image. The ideal behaviour should be to content the image in input box. Image must be centre aligned. You should share a demo with above scenario.

### Functionality Issues
- It seems you missed the types definitions for the new props

### Docs
- Add Docs PR for all the changes

**Comment by SavvyShah** [comment]
> ### UI Issues
> * Focus shortcut icon should have proper margins and padding, colors should match the theme.

What should be the margins and padding?

**Comment by SavvyShah** [comment]
Review changes: [Loom preview](https://www.loom.com/share/369c872f7b2d499c9c4c29237257ae86)

**Comment by SavvyShah** [comment]
https://www.loom.com/share/d046d007e21d409e85bccf3ed2069bf4

**Comment by SavvyShah** [comment]
[Loom preview](https://www.loom.com/share/d046d007e21d409e85bccf3ed2069bf4)

**Pull request merged**
