### PR TITLE
Vue - Expose item count on renderItem

### PR DESCRIPTION
**Pull request by royduin**
So we can do things conditionally on the product count.

### CODE REVIEW

**Comment by royduin** [comment]
Please merge @bietkul 😇

**Review by bietkul — APPROVED** [review]

**Comment by bietkul** [comment]
@royduin Can you please share the problem you're trying to solve?

**Comment by royduin** [comment]
We can now for example do this: https://github.com/rapidez/core/commit/0bf6762d444468c8098c38f4da13f06c70c7e84a#diff-f0a4735dbbab5c91c5f7a992e6ec81cb9f561150173a5ce15b3a3c1810e08106

**Comment by royduin** [comment]
Thanks for merging! 💯

**Pull request merged**
