### PR TITLE
 fix(native-site): update example links

### PR DESCRIPTION
**Pull request by lakhansamani**

### CODE REVIEW

**Review by bietkul — APPROVED** [review]

**Comment by siddharthlatest** [comment]
@lakhansamani Are we missing the build step here? The website isn't still updated.

**Comment by lakhansamani** [comment]
Shouldn't that be automated for sites?

**Comment by siddharthlatest** [comment]
We use gh-pages for these sites, and it's not automated here currently.

**Comment by lakhansamani** [comment]
Okay I checked code, we are using following scrip `deploy-site` to deploy website, so let me complete that step

**Pull request merged**
