### PR TITLE
feat(web): add support for unrated results in RatingsFilter

### PR DESCRIPTION
**Pull request by ShahAnuj2610**
https://github.com/appbaseio/reactivesearch/issues/267

### CODE REVIEW

**Comment by jyash97** [comment]
Hey, @ShahAnuj2610 Thanks for the PR.

Have you tested this by keeping `URLParams` as `true` ?

**Comment by ShahAnuj2610** [comment]
> Hey, @ShahAnuj2610 Thanks for the PR.
> 
> Have you tested this by keeping `URLParams` as `true` ?

@jyash97  fixed!

**Review by jyash97 — COMMENTED** [review]
@ShahAnuj2610 

The feature works well but there are some UI changes and testing needed while implementing this. Here are a few things that I noticed:

1. When I don't have `includeUnrated`, I see an extra comma in the tab. Check this: 
image

2. When we don't have `includeUnrated` the URL params just says `true` or `null` so either we should show `includedUnrated` or doesn't show. cc @siddharthlatest Thoughts?

3. There is a proptype error coming on selectedValue

4. We will also need to document these changes over [here](https://opensource.appbase.io/reactive-manual/range-components/ratingsfilter.html)

**Comment by siddharthlatest** [comment]
For 2., we don't need a URL query string for includeUnrated.

-Siddharth

**Review by jyash97 — APPROVED** [review]
@ShahAnuj2610  

These changes look good. Great Work! 💯 

Thanks for Contribution 🥂

**Pull request merged**
